Philanthropy Page
acm-ucr/iranian-student-association-website pull request #25
Opened 2024-10-16 05:45 UTC by bgarcia11

![Screenshot_2024-10-16_05-07-29_0](https://github.com/user-attachments/assets/8229cb8d-40d6-4714-9224-e0f00bd265e8)
-Added logos/images in public
-Added placeholders for button and footer components (so that it would compile)
-Added page component and imported it in app

2024-10-17 06:50 UTC, kavinphab commented
image check failed

2024-10-17 07:17 UTC, kavinphab requested changes

2024-10-17 07:17 UTC, kavinphab commented on public/philanthropy/IAWF.png
convert to svg

2024-10-17 07:17 UTC, kavinphab commented on public/philanthropy/childrenInternational.png
convert to svg

2024-10-19 23:32 UTC, bgarcia11 commented
![image](https://github.com/user-attachments/assets/4fbc603c-2786-4355-82e0-931cf0efefc4)

- Changed files to pass image check
- Made text smaller

2024-10-20 02:53 UTC, kavinphab approved these changes

2024-10-20 02:53 UTC, merged