Marcus hsieh/join us paisley
acm-ucr/iranian-student-association-website pull request #28
Opened 2024-10-17 22:43 UTC by MarcusHsieh

![image](https://github.com/user-attachments/assets/f20a4a57-59e5-4fc9-98a3-45da5327c53e)

2024-10-17 22:45 UTC, MarcusHsieh commented
Created socials and part of the calendar to make sure the paisleys were working.

- `socials.tsx` data in `icons.ts` 
 - Didn't put in links

2024-10-17 23:22 UTC, MarcusHsieh commented
NOTE: Paisleys are in `.webp` format.

2024-10-18 05:51 UTC, kavinphab requested changes
You have some merge conflicts

2024-10-20 02:46 UTC, kavinphab approved these changes

2024-10-20 02:46 UTC, merged