Dennyhly/gallery button
acm-ucr/iranian-student-association-website pull request #29
Opened 2024-10-18 00:19 UTC by dennyhly

![Screenshot (21)](https://github.com/user-attachments/assets/16d99042-91db-47f5-98d3-102c021d4eec)
![Screenshot (22)](https://github.com/user-attachments/assets/b3bad8b2-4903-4856-bbe1-253f6073fbf6)
-Created gallery button that took in a name as a prop
-Added paisley1 and 2
-Closes #11

2024-10-18 05:57 UTC, kavinphab requested changes

2024-10-18 05:57 UTC, kavinphab commented on src/app/gallery/page.tsx
page.tsx files should only be calling related components, move paisleys to their own component as well as the mapping and just call it in this page file, also make paisleys and buttons smaller they look big with relation to the nav bar

2024-10-20 03:00 UTC, kavinphab commented on src/app/gallery/page.tsx
you can refer to some of the other merged components for reference

2024-10-22 07:45 UTC, dennyhly commented on src/app/gallery/page.tsx
![Screenshot (23)](https://github.com/user-attachments/assets/30e16bbf-7343-43cc-8db1-76b4f7151060)
![Screenshot (24)](https://github.com/user-attachments/assets/4a6d7874-bdc3-49f4-bbfa-050410810654)
-Moved paisley and mapping to their own component files
-shrunk the size of paisleys and buttons

2024-10-22 15:58 UTC, kavinphab approved these changes

2024-10-22 15:58 UTC, merged